name: python-env-setup-gliss
author: "Davide Corso"
description: "Creates a Python virtual environment for GLISS"

inputs:
  workdir:
    description: "Path of the working directory"
    required: true

  extra_deps:
    description: "Extra packages to be installed in the environment"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Create the virtual environment
      shell: bash
      run: |
        cd '${{ inputs.workdir }}'
        python3 -m venv .venv

    - name: Install requirements
      shell: bash
      run: |
        cd '${{ inputs.workdir }}'
        . .venv/bin/activate
        export LLVM_CONFIG=/usr/bin/llvm-config-7
        pip install --upgrade pip
        pip install --upgrade setuptools
        pip install --upgrade wheel
        pip install --upgrade cython
        pip install numpy==1.20
        [ -z "${{ inputs.extra_deps }}" ] || pip install ${{ inputs.extra_deps }}
        pip install -r requirements.txt
